import { JobState, Segment, SystemStatus } from '@/types';

export const MOCK_SYSTEM_STATUS: SystemStatus = {
  gpu_name: 'NVIDIA GeForce RTX 2070 SUPER (8GB VRAM)',
  gpu_vram_used_bytes: 4124966912, // 3.84 GB
  gpu_vram_total_bytes: 8589934592, // 8.0 GB
  gpu_utilization_pct: 64,
  cpu_utilization_pct: 28,
  active_jobs_count: 1,
  webgpt_connected: true,
  webgpt_model: 'chatgpt-web/gpt-5.6-sol',
  webgpt_port: 17842,
  server_uptime_seconds: 14280,
  websocket_connected: true,
};

export const MOCK_SEGMENTS: Segment[] = [
  {
    id: 0,
    start: 0.13,
    end: 4.41,
    text: 'When the market opens, confirm the trend before entering a position.',
    vi: 'Khi thị trường mở cửa, hãy xác nhận xu hướng rõ ràng rồi mới vào lệnh.',
    speaker: 'SPEAKER_00',
    review_status: 'accepted',
    rewritten: false,
    overflow: false,
    semantic_flag: false,
    speaker_overlap: false,
    multi_speaker: false,
    flagged: false,
    avg_logprob: -0.015,
    target_duration: 4.28,
    actual_duration: 4.15,
    source_audio_url: 'https://actions.google.com/sounds/v1/speech/commercial_speech_mono.ogg',
    dub_audio_url: 'https://actions.google.com/sounds/v1/speech/commercial_speech_mono.ogg',
  },
  {
    id: 1,
    start: 4.61,
    end: 7.95,
    text: 'Keep the risk small and write down the reason for every trade.',
    vi: 'Giữ mức rủi ro thật thấp và ghi lại lý do cụ thể cho từng vị thế giao dịch.',
    speaker: 'SPEAKER_00',
    review_status: 'reviewed',
    rewritten: true,
    overflow: false,
    semantic_flag: false,
    speaker_overlap: false,
    multi_speaker: false,
    flagged: false,
    avg_logprob: -0.021,
    target_duration: 3.34,
    actual_duration: 3.28,
    source_audio_url: 'https://actions.google.com/sounds/v1/speech/commercial_speech_mono.ogg',
    dub_audio_url: 'https://actions.google.com/sounds/v1/speech/commercial_speech_mono.ogg',
  },
  {
    id: 2,
    start: 8.20,
    end: 13.45,
    text: 'Notice how the 200 EMA acts as dynamic support on the four-hour timeframe.',
    vi: 'Hãy quan sát cách đường EMA 200 đóng vai trò hỗ trợ động mạnh mẽ trên khung thời gian 4 giờ.',
    speaker: 'SPEAKER_00',
    review_status: 'needs_review',
    rewritten: true,
    overflow: true,
    semantic_flag: false,
    speaker_overlap: false,
    multi_speaker: false,
    flagged: true,
    avg_logprob: -0.042,
    target_duration: 5.25,
    actual_duration: 5.48, // Overflow > 3%
    source_audio_url: 'https://actions.google.com/sounds/v1/speech/commercial_speech_mono.ogg',
    dub_audio_url: 'https://actions.google.com/sounds/v1/speech/commercial_speech_mono.ogg',
  },
  {
    id: 3,
    start: 13.80,
    end: 18.15,
    text: 'If volume spikes without price progress, that is clear absorption by smart money.',
    vi: 'Nếu khối lượng giao dịch đột biến mà giá không bứt phá, đó là dấu hiệu hấp thụ của dòng tiền lớn.',
    speaker: 'SPEAKER_01',
    review_status: 'unreviewed',
    rewritten: false,
    overflow: false,
    semantic_flag: true,
    speaker_overlap: false,
    multi_speaker: false,
    flagged: true,
    avg_logprob: -0.018,
    target_duration: 4.35,
    actual_duration: 4.20,
    source_audio_url: 'https://actions.google.com/sounds/v1/speech/commercial_speech_mono.ogg',
    dub_audio_url: 'https://actions.google.com/sounds/v1/speech/commercial_speech_mono.ogg',
  },
  {
    id: 4,
    start: 18.50,
    end: 22.90,
    text: 'Never move your stop loss further away once the order is active in the market.',
    vi: 'Tuyệt đối không dời điểm cắt lỗ ra xa hơn một khi lệnh đã được khớp trên thị trường.',
    speaker: 'SPEAKER_01',
    review_status: 'accepted',
    rewritten: false,
    overflow: false,
    semantic_flag: false,
    speaker_overlap: true,
    multi_speaker: true,
    flagged: true,
    avg_logprob: -0.012,
    target_duration: 4.40,
    actual_duration: 4.31,
    source_audio_url: 'https://actions.google.com/sounds/v1/speech/commercial_speech_mono.ogg',
    dub_audio_url: 'https://actions.google.com/sounds/v1/speech/commercial_speech_mono.ogg',
  },
  {
    id: 5,
    start: 23.10,
    end: 27.60,
    text: 'Execution discipline determines your long-term expectancy far more than entry precision.',
    vi: 'Kỷ luật thực thi quyết định lợi nhuận kỳ vọng dài hạn hơn nhiều so với việc căn ke điểm vào.',
    speaker: 'SPEAKER_00',
    review_status: 'unreviewed',
    rewritten: false,
    overflow: false,
    semantic_flag: false,
    speaker_overlap: false,
    multi_speaker: false,
    flagged: false,
    avg_logprob: -0.019,
    target_duration: 4.50,
    actual_duration: 4.42,
    source_audio_url: 'https://actions.google.com/sounds/v1/speech/commercial_speech_mono.ogg',
    dub_audio_url: 'https://actions.google.com/sounds/v1/speech/commercial_speech_mono.ogg',
  },
];

export const MOCK_JOBS: JobState[] = [
  {
    id: 'job-818d0c0945f59098',
    created_at: new Date(Date.now() - 320000).toISOString(),
    updated_at: new Date(Date.now() - 40000).toISOString(),
    status: 'completed',
    stage: 'complete',
    progress: 1.0,
    message: 'Hoàn tất quy trình xử lý & kiểm định chất lượng',
    metadata: {
      input_name: 'Trading_Psychology_Masterclass.mp4',
      youtube_url: 'https://www.youtube.com/watch?v=tW13N4Hll88',
      output: 'D:\\ANNAM\\TradingWorkspace\\projects\\vi-dubber\\work\\outputs\\Trading_Psychology_vi.mp4',
      profile: 'balanced_best',
      translation_model: 'chatgpt-web/gpt-5.6-sol',
      translation_model_display_name: 'GPT-5.6 Sol (Codex Web)',
      translation_effort: 'high',
      translation_provider: 'webgpt',
      source_mode: 'YouTube',
      diarization: 'PyAnnote Speaker Clustering',
    },
    result: {
      duration_seconds: 184.5,
      elapsed_seconds: 142.8,
      real_time_factor: 0.77, // 0.77x (1.3x faster than real time)
      segments: 6,
      speaker_count: 2,
      speakers: ['SPEAKER_00', 'SPEAKER_01'],
      overflow_segments: 1,
      rewritten_segments: 2,
      cloned_segments: 2,
      average_tempo: 1.02,
      max_tempo: 1.15,
      output: 'D:\\ANNAM\\TradingWorkspace\\projects\\vi-dubber\\work\\outputs\\Trading_Psychology_vi.mp4',
      subtitle: 'D:\\ANNAM\\TradingWorkspace\\projects\\vi-dubber\\work\\outputs\\Trading_Psychology_vi.srt',
      mix: {
        integrated_lufs: -14.2,
        true_peak_db: -1.6,
        loudness_delta_lu: -0.2,
        loudness_range_lu: 5.4,
        passes_loudness: true,
        passes_true_peak: true,
        target_lufs: -14.0,
        target_true_peak_db: -1.5,
        clipping_risk: false,
      },
      qa: {
        similarity: 0.948,
        threshold: 0.78,
        passed: true,
        global_passed: true,
        segment_summary: {
          segments_checked: 6,
          initial_failed: 1,
          repairs_attempted: 1,
          repairs_completed: 1,
          final_failed: 0,
          passed: true,
        },
      },
      semantic_qa: {
        mode: 'verify_escalate',
        translated_status: 'ok',
        rewritten_status: 'ok',
        translated_checked: 6,
        translated_needs_review: 1,
      },
      voice_track: {
        peak: 0.78,
        peak_dbfs: -2.16,
        clipping_ratio: 0.0,
      },
      translation: {
        model: 'chatgpt-web/gpt-5.6-sol',
        provider: 'webgpt',
        prefit_rewrite_calls: 2,
        rewrite_calls: 1,
        webgpt_attempts: 2,
      },
    },
    metrics: {
      schema_version: 1,
      total_wall_seconds: 142.8,
      stages: {
        input_extract: { wall_seconds: 2.1, calls: 1, failed_calls: 0 },
        separation: { wall_seconds: 18.4, calls: 1, failed_calls: 0 },
        asr: { wall_seconds: 24.2, calls: 1, failed_calls: 0 },
        translation: { wall_seconds: 46.5, calls: 1, failed_calls: 0 },
        tts_pass_1: { wall_seconds: 28.1, calls: 1, failed_calls: 0 },
        mix_mux: { wall_seconds: 6.8, calls: 1, failed_calls: 0 },
        acoustic_qa: { wall_seconds: 16.7, calls: 1, failed_calls: 0 },
      },
      counters: {
        source_segments: 6,
        speech_turns: 6,
        translation_calls: 2,
        webgpt_batches: 1,
        rewrite_calls: 2,
        typesafe_requests: 6,
        typesafe_tokens: 4120,
        tts_inferences: 8,
        tts_batches: 1,
        cache_hits: 4,
        cache_misses: 2,
        qa_repairs: 1,
        webgpt_attempts: 2,
        webgpt_failures: 0,
      },
      resources: {
        torch_cuda_allocator: {
          available: true,
          device_name: 'NVIDIA GeForce RTX 2070 SUPER',
          device_index: 0,
          allocated_bytes: 4124966912,
          reserved_bytes: 4898947072,
          peak_allocated_bytes: 5410652160,
          peak_reserved_bytes: 6100000000,
        },
      },
    },
  },
  {
    id: 'job-d2949bc6672e42a8',
    created_at: new Date(Date.now() - 65000).toISOString(),
    updated_at: new Date().toISOString(),
    status: 'running',
    stage: 'tts',
    progress: 0.62,
    message: 'Đang tổng hợp giọng nói tiếng Việt cho Segment 4/6 (Kokoro neural)',
    metadata: {
      input_name: 'Crypto_Derivatives_Breakdown.mp4',
      youtube_url: 'https://www.youtube.com/watch?v=kY876xAbcd',
      profile: 'max_quality',
      translation_model: 'chatgpt-web/gpt-5.6-sol',
      translation_model_display_name: 'GPT-5.6 Sol (Web)',
      translation_effort: 'extra_high',
      translation_provider: 'webgpt',
      source_mode: 'Local',
      diarization: 'PyAnnote Speaker Clustering',
    },
    metrics: {
      total_wall_seconds: 65.0,
      stages: {
        input_extract: { wall_seconds: 1.8, calls: 1, failed_calls: 0 },
        separation: { wall_seconds: 16.2, calls: 1, failed_calls: 0 },
        asr: { wall_seconds: 22.0, calls: 1, failed_calls: 0 },
        translation: { wall_seconds: 25.0, calls: 1, failed_calls: 0 },
      },
      counters: {
        source_segments: 6,
        speech_turns: 6,
        translation_calls: 3,
        webgpt_batches: 2,
        rewrite_calls: 1,
        typesafe_requests: 4,
        typesafe_tokens: 2840,
        tts_inferences: 4,
        tts_batches: 1,
        cache_hits: 1,
        cache_misses: 3,
      },
      resources: {
        torch_cuda_allocator: {
          available: true,
          device_name: 'NVIDIA GeForce RTX 2070 SUPER',
          device_index: 0,
          allocated_bytes: 3870000000,
          reserved_bytes: 4500000000,
          peak_allocated_bytes: 4800000000,
          peak_reserved_bytes: 5200000000,
        },
      },
    },
  },
];
